### ISSUE TITLE
Cake Release Issue Template

### ISSUE THREAD

**Issue by gep13** [cake-build/processes#2]
## Useful information

* [AppVeyor builds](https://ci.appveyor.com/project/cakebuild/cake)
* [Travis builds](https://travis-ci.org/cake-build/cake)

### Manual Approach

- [ ] Add the CAKE_GITHUB_USERNAME and CAKE_GITHUB_PASSWORD environment variables into your system. These should be of a user who has access to the Cake GitHub Repository.
- [ ] Make sure `develop` branch of `cake-build/cake` is up to date `git fetch` then `git rebase origin/develop`.
- [ ] Make sure `main` branch of `cake-build/cake` is up to date `git fetch` then `git rebase origin/main`.
- [ ] Make sure `develop` branch of `cake-build/website` is up to date `git fetch` then `git rebase origin/develop`.
- [ ] Make sure `master` branch of `cake-build/website` is up to date `git fetch` then `git rebase origin/master`.
- [ ] Make sure `master` branch of `cake-build/example` is up to date `git fetch` then `git rebase origin/master`.
- [ ] Make sure `develop` branch of `cake-build/resources` is up to date `git fetch` then `git rebase origin/develop`.
- [ ] Make sure `master` branch of `cake-build/resources` is up to date `git fetch` then `git rebase origin/master`.
- [ ] Make sure that all issues associated with pull requests getting released in this milestone are associated with the milestone, or that the pull request is associated with the milestone, if no issue was created.
- [ ] Make sure you have a fork of `Homebrew/homebrew-core`
- [ ] Make sure upstream points at `Homebrew/homebrew-core`
- [ ] Make sure `master` branch of `Homebrew/homebrew-core` is up to date; `git fetch` then `git rebase upstream/master`.

### Automated Approach
- [ ] Make sure you have a fork of `Homebrew/homebrew-core`.
- [ ] Run the `Prereqs.ps1` file, using the following as an example `.\Prereqs.ps1 -GithubUsername gep13` (use your own username). This will clone a new version of all required repositories.

## Let people know that things are happening...

- [ ] Go to the Gitter room for Cake and inform people that a release is away to happen.  Use a message similar to the following `@/all We will soon start preparing for the [0.31.0 release](https://github.com/cake-build/cake/milestone/54?closed=1) of Cake. So this is a friendly reminder to pin your Cake version.`
- [ ] Go to the Gitter room for Cake-Contrib and inform people that a release is away to happen.  Use a message similar to the following `@/all We will soon start preparing for the [0.31.0 release](https://github.com/cake-build/cake/milestone/54?closed=1) of Cake. So this is a friendly reminder to pin your Cake version.`
- [ ] Go to the General Channel in the Slack Team for Cake-Contrib and inform people that a release is away to happen.  Use a message similar to the following `@channel We will soon start preparing for the 0.31.0 release ( https://github.com/cake-build/cake/milestone/54?closed=1 ) of Cake. So this is a friendly reminder to pin your Cake version.`
- [ ] Using the Cake Twitter account, tweet to let people know that the release is away to happen.  Use something like the following `We are starting to prepare our next release, 0.31.0 (https://github.com/cake-build/cake/milestone/54?closed=1).  This is your friendly reminder that if you haven't pinned to a specific version of Cake, you should do it now :-) https://cakebuild.net/docs/tutorials/pinning-cake-version`
- [ ] Retweet the above from the cake-contrib twitter account

## GitHub Issues Pre-requisites

- [ ] Make sure all issues within the milestone are tagged with either Bug, Feature, Improvement, Documentation, Breaking change, or Build
- [ ] Make sure all issues associated with the milestone are closed
- [ ] Make sure that all issues only have 1 label associated with them

## When doing a release

- [ ] Create branch locally to match the name of the release, for example `git checkout -b release/0.31.0 develop`
- [ ] Update `releasenotes.md` to include next version number as a placeholder and save the file
- [ ] Create release notes on GitHub using the `ReleaseNotes` task (`.\build.ps1 --target=ReleaseNotes`)
- [ ] Update `releasenotes.md` with generated content (making sure to keep the formatting the same)
- [ ] Build everything (`./build.ps1`) to make sure it works.
- [ ] Commit the changes to `releasenotes.md` and `solutioninfo.cs`. Use comment like `(build) Updated version and release notes.`
- [ ] At this point, if you want to share the work to date, and validate something, push the local release branch to GitHub
- [ ] Assuming everything is ok, switch to `main` branch (`git checkout main`)
- [ ] Merge release branch to the `main` `git merge --no-ff release/0.31.0`
- [ ] Build everything (`./build.ps1`) to make sure it works (we can never be too sure).
- [ ] Push `main` branch.
- [ ] Make sure that both the [AppVeyor](https://ci.appveyor.com/project/cakebuild/cake), [Bitrise Ubuntu](https://www.bitrise.io/app/b811c91a26b1ea80#/builds) and [Bitrise OSX](https://www.bitrise.io/app/7a9d707b00881436#/builds) builds succeed before going any further.
- [ ] Assuming that everything went ok, go to the draft release in GitHub and click Edit
- [ ] Click the Publish Release button
- [ ] This will trigger another build in AppVeyor, but this time with a tag.
- [ ] From the AppVeyor Log, take a note of the generated Hash from the `Publish-HomeBrew` task 
- [ ] Switch to `develop` branch `git checkout develop`
- [ ] Merge release branch into develop `git merge --no-ff release/0.31.0`
- [ ] Resolve any merge conflicts
- [ ] Bump the Cake Tool Version number in `build.config` to the latest released version, i.e. the version you just released
- [ ] Build everything (`./build.ps1`) to make sure it works.
- [ ] Commit the changes to `build.ps1` and `build.sh`  **NOTE:** There will be other changes to the *.json files as well, commit everything. Use commit message like `(build) Updated Cake tool to version 0.31.0`
- [ ] Push `develop` branch.
- [ ] Delete the local release branch that was created `git branch -d release/0.31.0` (and the remote one, if pushed to GitHub `git push origin --delete release/0.31.0`)

## After a release/hotfix

- [ ] Make sure that everything has pushed correctly to nuget
    * [Cake](https://www.nuget.org/packages/Cake/)
    * [Cake.Core](https://www.nuget.org/packages/Cake.Core/)
    * [Cake.CoreCLR](https://www.nuget.org/packages/Cake.CoreCLR/)
    * [Cake.Common](https://www.nuget.org/packages/Cake.Common/)
    * [Cake.Testing](https://www.nuget.org/packages/Cake.Testing/)
    * [Cake.NuGet](https://www.nuget.org/packages/Cake.NuGet/)
    * [Cake.Tool](https://www.nuget.org/packages/Cake.Tool/)
- [ ] Make sure that everything has pushed correctly to chocolatey
    * [cake.portable](https://chocolatey.org/packages/cake.portable) **NOTE:** This package might be subject to moderation, and might not appear immediately
- [ ] Move to homebrew repository
- [ ] Create a new branch for current release `git checkout -b cake-0.31.0`
- [ ] Open the `Formula/cake.rb`
- [ ] Update the url (line 4) to be the new download location
- [ ] Update the sha256 (line 5) to be the value that was generated earlier by the `Publish-HomeBrew` task
- [ ] Commit the changes to `cake.rb`  **NOTE:** Commit message should use the following format `cake 0.31.0`  **NOTE:** Make sure to use a lower case `C` as that is the [preferred formatting in the Homebrew repo](https://github.com/Homebrew/homebrew-core/pull/4857#issuecomment-247475453)
- [ ] Push the new branch to your fork
- [ ] Open a PR against the `master` branch of `Homebrew/homebrew-core`
- [ ] Move to example repository
- [ ] Open the `tools/packages.config` file
- [ ] Update the Cake version number to be the same as the version that you have just released
- [ ] Build everything (`./build.ps1` or `./build.sh`) to make sure it works.
- [ ] Commit changes. Use message similar to `(build) Updated Cake tool to version 0.31.0`
- [ ] Push branch
- [ ] Move to resources repository
- [ ] Switch to the develop branch `git checkout develop`
- [ ] Open the `packages.config` file
- [ ] Update the Cake version number to be the same as the version that you have just released
- [ ] Commit changes. Use message similar to `(build) Updated Cake tool to version 0.31.0`
- [ ] Push branch `git push`
- [ ] Switch to the master branch `git checkout master`
- [ ] Merge changes from develop branch `git merge --no-ff develop`
- [ ] Push branch `git push`
- [ ] Move to website repository
- [ ] Create a branch for a new blog post `git checkout -b 0.31.0-Blog-Post develop`
- [ ] Create Blog Post i.e. `.\input\blog\2018-07-06-cake-v0.31.0-released.md`
- [ ] You can get contibutors and stub for blog post using the console `secrets\Processes\FetchContributors`
    * dotnet restore
    * dotnet run "cake-build" "cake" "v0.30.0" "[last commit id develop]" "[path to website]/input/blog" "v0.31.0"
- [ ] Bump the Cake Tool Version number in `tools\package.config` to the latest released version, i.e. the version you just released
- [ ] Commit changes to `tools\package.config` file using message similar to `(build) Updated Cake tool to version 0.31.0`
- [ ] Commit blog post using message similar to `v0.31.0 Blog Post`
- [ ] Push branch and submit pull request
- [ ] Make sure that the [AppVeyor](https://ci.appveyor.com/project/cakebuild/website) build succeeds successfully
- [ ] Have someone else verify the contents
- [ ] Merge the Pull Request
- [ ] Go to [develop.cakebuild.net](https://develop.cakebuild.net) once you receive the Azure notification in Slack to say that the development site is deployed.  Make sure that it works as expected.
- [ ] Switch to `develop` branch `git checkout develop`
- [ ] Update local develop branch `git fetch` then `git rebase origin/develop`
- [ ] Delete local branch that was created `git branch -d 0.31.0-Blog-Post`
- [ ] Switch to `master` branch `git checkout master`
- [ ] Merge `develop` to `master`  `git merge --no-ff develop` **NOTE:** This will also update the documentation for the various Addins/Tools on the site, so if any new aliases have been added, these will be included in the build.
- [ ] Push `master` branch `git push`
- [ ] Go to [cakebuild.net](https://cakebuild.net/) once you receive the Azure notification in Slack to say that the development site is deployed.  Make sure that it works as expected.
- [ ] Go to the Cake-Contrib Gitter Room and let people know that it was released.  Use something like `@/all Version 0.31.0 of the Cake has just been released, https://www.nuget.org/packages/Cake.`
- [ ] Go to the Cake-Contrib Slack Team and in the General Room let people know that it was released.  Use something like `@channel Version 0.31.0 of the Cake has just been released, https://www.nuget.org/packages/Cake.`
- [ ] Go to the [On .Net Link submission form](https://weekindotnet.azurewebsites.net/) and add link to the post
- [ ] Go to reddit and submit link [reddit.com/r/dotnet](https://reddit.com/r/dotnet), 
- [ ] Go to [LinkedIn](https://www.linkedin.com/company/17902391/admin/) and create a new post
  - [ ] Click on Manage Page
  - [ ] Add link and then click Post
- [ ] Go to [Medium](https://medium.com/@cakebuildnet) and import the story.
  - [ ] Log into Medium as the cake-build twitter user
  - [ ] Click on the Cake logo at top right of screen, then click on Stories
  - [ ] Click on Import a Story
  - [ ] Enter url of blog post and click Import (if this errors out, just try it again)
  - [ ] Click on see your story
  - [ ] Remove the first line of the imported story
  - [ ] Click Publish and enter the tags`DevOps` `Csharp` `Release Notes` `Dotnet` `Continuous Integration`
  - [ ] Click Publish
- [ ] Go to the Cake Slack Channel and share the links to Medium, LinkedIn and reddit so that other team members can share them
- [ ] Go and have a drink!

**Comment by Jericho** [comment]
I suggest adding the following bullet point under the `GitHub Issues` section:
- [ ] Raise an issue in the Cake.AddinDiscoverer repo **if there are any breaking changes** so the discoverer can be modified to generate a new markdown report and also Excel report to track which addins are compatible with this new release of Cake.

**Comment by gep13** [comment]
That seems like a great addition to me!

**Comment by gep13** [comment]
@cake-build/cake-team I am going to close this issue in favour of the new issue template that I have created here:

https://github.com/cake-build/processes/blob/master/.github/ISSUE_TEMPLATE/new-cake-release.md

If anyone has any updates/changes to the template, please update the template file.
